### ISSUE TITLE
Expose your user ID in the API

### ISSUE THREAD

**Issue by BrianStephens** [accredible/accredible-api-ruby#5]
Hi,

We've got almost all the hooks we need to direct our admins straight into your admin UI for a given user cert from the info we pull from your API. What we still need is what I presume is your User ID (see URL Below). Is it possible to expose this?
https : / / dashboard.accredible.com/issuer/dashboard/group/[group_id]/credential/[yourUserID]

There could be cases where either we haven't yet implemented an API yet to perform some admin functions or those hooks don't yet exist and can only be accessed in your admin UI. Assuming admins with expired sessions are redirected to the destination URL, we could deeplink admins to those features.

**Comment by deependersingla** [comment]
Hi @BrianStephens ,

This URL is actually:
https : / / dashboard.accredible.com/issuer/dashboard/group/[group_id]/credential/[AccredibleCertificateID]

If you are not using custom id for credential creation then you will find it in all endpoints with id as key, otherwise (if you are using license id) please let me know which endpoint you are using I will add a field to it called AccredibleCertificateID. 

Does that answer your question?

**Comment by deependersingla** [comment]
Hi @BrianStephens ,

Closing this, Please let me know if you need anything more?

**Comment by BrianStephens** [comment]
All set, thanks!
